root = "."
tmp_dir = "tmp/air"

[build]
cmd = "go build -trimpath -ldflags='-s -w' -o ./tmp/air/taskbridge ."
bin = "./tmp/air/taskbridge"
args_bin = ["serve"]
delay = 1000
include_ext = ["go", "yaml", "yml", "toml"]
exclude_dir = ["dist", "build", "temp", "tmp", "vendor", ".git"]
exclude_regex = ["_test.go"]
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
